### ISSUE TITLE
Login link seems to be broken.

### ISSUE THREAD

**Issue by thekaushikls** [pm-Architect/Verse3#10]
## Steps to reproduce
1. Download `EARLY Release | Win64` from [here](https://github.com/iiterate-de/Verse3/releases/tag/Win64)
2. Install, and run as Admin.
3. Open application, and click on `🔑 Key` icon.
    <img src="https://user-images.githubusercontent.com/50703773/219416165-affd377a-e03a-40db-a474-e66ca14bda0b.png" width=512>
5. Close browser window, and try again.
    <img src="https://user-images.githubusercontent.com/50703773/219415942-adfa732d-8952-43e5-98a6-ba665819d2ed.png" width=512>

**Comment by pm-Architect** [comment]
Sorry about that @thekaushikls 
If there are no users logging in, supabase auto-pauses projects on the free tier. I've unpaused the project, so it should work now. If this happens again, ping me.
